name: CI

on:
  push:
  pull_request:

jobs:
  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
      - name: Test
        run: dotnet test Blazor.WorkflowEditor.Tests/Blazor.WorkflowEditor.Tests.csproj -c Release
      - name: Build Web
        run: dotnet build WorkflowEditor.Web/WorkflowEditor.Web.csproj -c Release
